name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: "header, repositories"
          plugin_isocalendar: "yes"

      - name: Verify metrics file existence
        run: |
          if [ ! -f "github-metrics.svg" ]; then
            echo "Error: File github-metrics.svg not found!"
            exit 1
          fi

      - name: Commit and push metrics
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-metrics.svg
          git commit -m "Update metrics"
          git push
